# name: String - Name of node
# cpu: int or float - Number of CPUs
# memory: int - Memory size in Megabyte (smallest node size support 1MB)

resources:
  - name: node-1
    cpu: 2
    memory: 2048
  - name: node-2
    cpu: 4
    memory: 4096
  - name: node-3
    cpu: 0.5
    memory: 512
