# name: String - Name of node
# cpu: int or float - Number of CPUs
# memory: int - Memory size in Megabyte (smallest node size support 1MB)

resources:
  - name: node-1
    cpu: 2
    memory: 8000
    labels:
      cloud: public
  - name: node-2
    cpu: 3
    memory: 3000
  - name: node-3
    cpu: 4
    memory: 4000
